wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1696429475.837314
    t:
      1:
      - 55
      - 95
      - 105
      2:
      - 55
      - 95
      - 105
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
